### ISSUE TITLE
MRC retraining after 119 boots

### ISSUE THREAD

**Issue by krunoPeric** [slimbootloader/slimbootloader#146]
For fast boot, after 119 boots, the memory training process repeats.  This causes an unacceptably long boot time.

**Comment by mauricema** [comment]
We have reproduced this issue by doing reboot cycles.  Part of the debug log is attached below:
[Sbl_Dbg.log](https://github.com/slimbootloader/slimbootloader/files/3117697/Sbl_Dbg.log)

In boot cycle 119  (search for "Use slot 119" in log),  everything still worked fine.   However, the next boot cycle after it,  it shows "MRC data NOT found".  It indicates SBL could not find valid MRC NVS data saved by previous boot.

After debugging, it turned out to be some boundary condition issue NVS data management in APL platform code.  The last MRC NVS slot entry should be used for retrieving data when all slots are marked as used.  However, the current code logic will just return EFI_NOT_FOUND if all slots are marked in use.
