### ISSUE TITLE
[EHL] STMMAC: change MTU to a bigger value(>1508) will cause large frame(>1476)  blocked

### ISSUE THREAD

**Issue by sharkblue2009** [slimbootloader/slimbootloader#2026]
Hi,

On EHL board and Ubuntu OS,  when we change the lan port (stmmac) mtu to a bigger value: >=1508, will cause big frame(>1476 bytes) be blocked somewhere, but when the mtu is 1500 or less than 1508, everything is ok. we are not sure if there are fix in stmmac driver,  or howto workaround it.

test script:
`
ifconfig enp0s29f1 down
ifconfig enp0s29f1 mtu 1508
ifconfig enp0s29f1 up

ping -s 2000 192.168.1.1
ping -s 1476 192.168.1.1
`

OS:
Ubuntu 22.04/5.15.0-1026-intel-iotg

**Comment by stanleyintel** [comment]
Hi Sharkblue,

   I am not aware of the MTU configuration in SBL/FSP, but please tell me any clues if you have.

   So far I find a doc talking about ethernet throughput. On page 15 of RDC# 679737, it describes the MTU configuration in their throughput test. Maybe you can check the commands they use. Note that the same document also mentions some BIOS settings, but it should be not related to your case.
 
   Because the issue is out of the scope of SBL, to get help from Gbe team, please file an IPS case. Note that you need to follow RDC# 703916 when submitting an ethernet issue for EHL platform.
