### ISSUE TITLE
[APL] SMBIOS sample info stub code is missing

### ISSUE THREAD

**Issue by umaplehurst** [slimbootloader/slimbootloader#391]
CFL has useful sample SMBIOS info stub code as part of `InitializeSmbiosInfo` in `Stage2BoardInitLib.c`. It would be helpful if this could be duplicated across to APL, or perhaps even better if it could be factored out into something generic to be used between platforms?

**Comment by rprangar** [comment]
Generalizing this function is a good suggestion. We will explore doing this in the near future. 

Thanks for the feedback. BTW, since this is not strictly an issue, mailing list may be a good place to post this suggestion.

Mailing List
You can subscribe to our mailing list for questions or share your learnings: https://lists.01.org/postorius/lists/sbl-devel.lists.01.org/

Archives:  https://lists.01.org/hyperkitty/list/sbl-devel@lists.01.org/
