### ISSUE TITLE
Failed to build QEMU FSP binary

### ISSUE THREAD

**Issue by jacendi** [slimbootloader/slimbootloader#474]
I'm trying to build Slim Bootloader with UEFI payload for QEMU (using GCC 9.2.1), but an error (unknown symbol FspSecCoreT:_TempRamInitApi) occurs at the post-build stage of QEMUFSP. [Here's a part of log](https://pastebin.com/95g6fzak)

What could be the reason for this error? Thanks in advance for help.

**Comment by mauricema** [comment]
I think it is caused by the GCC version.  GCC 5.x, 6.x, 7.x have been tested.  
Please use GCC 7.x instead.

The reason for this error could be some more aggressive optimization done at link time in newer GCC version.  Since this API will not be called directly inside FSP itself,  the linker might have removed it from the final binary.  As a result, and the symbol could not be located.

**Comment by jacendi** [comment]
Thanks! Yeah, it's compiles fine with GCC 7.x.

**Comment by luojia65** [comment]
Does this issue happen again? I can't build as well for `unknown symbol FspSecCoreT:_TempRamInitApi`
